# Generated by Django 5.0 on 2023-12-09 18:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums_coordinator', to='accounts.profile')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='albums', to='medias.image')),
                ('listeners', models.ManyToManyField(related_name='albums_listeners', to='accounts.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1255, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sounds', to='musics.album')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sounds', to='medias.audio')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sounds', to='accounts.profile')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sounds', to='medias.image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
