# Generated by Django 5.0 on 2023-12-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_description_alter_profile_name'),
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='listeners',
            field=models.ManyToManyField(blank=True, related_name='albums_listeners', to='accounts.profile'),
        ),
    ]
